// <auto-generated />
using System;
using GestionSallesEtEDT.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionSallesEtEDT.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521123418_Update_Enseignant_Model")]
    partial class Update_Enseignant_Model
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.AnneeUniversitaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_annee");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("date_debut");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("date_fin");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("libelle_annee");

                    b.HasKey("Id");

                    b.ToTable("annees_universitaires");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cla");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("niveau_cla");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_cla");

                    b.HasKey("Id");

                    b.ToTable("classes");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.EmploiDuTemps", b =>
                {
                    b.Property<int>("IdEdt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_edt");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEdt"));

                    b.Property<DateOnly>("DateCreation")
                        .HasColumnType("date")
                        .HasColumnName("date_creation");

                    b.Property<DateOnly?>("DateModification")
                        .HasColumnType("date")
                        .HasColumnName("date_modification");

                    b.Property<int>("IdAnnee")
                        .HasColumnType("integer")
                        .HasColumnName("id_annee");

                    b.Property<int>("IdClasse")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.Property<int>("IdSemestre")
                        .HasColumnType("integer")
                        .HasColumnName("id_semestre");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("libelle_edt");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut");

                    b.HasKey("IdEdt");

                    b.HasIndex("IdAnnee");

                    b.HasIndex("IdClasse");

                    b.HasIndex("IdSemestre");

                    b.ToTable("emplois_du_temps", (string)null);
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Enseignant", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id_enseignant");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email_ensei");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_enseignant");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom_enseignant");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone_ensei");

                    b.HasKey("Id");

                    b.ToTable("enseignants");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Etudiant", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id_etudiant");

                    b.Property<int>("ClasseId")
                        .HasColumnType("integer")
                        .HasColumnName("id_cla");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("matricule_etu");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.ToTable("etudiants");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Matiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_matiere");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_matiere");

                    b.Property<double>("Coefficient")
                        .HasColumnType("double precision")
                        .HasColumnName("coefficient_matiere");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("libelle_matiere");

                    b.HasKey("Id");

                    b.ToTable("matieres");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Salle", b =>
                {
                    b.Property<int>("id_salle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_salle"));

                    b.Property<string>("code_salle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("type_salle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_salle");

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Seance", b =>
                {
                    b.Property<int>("id_seance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_seance");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_seance"));

                    b.Property<int?>("EmploiDuTempsIdEdt")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("heure_debut")
                        .HasColumnType("interval")
                        .HasColumnName("heure_debut");

                    b.Property<TimeSpan>("heure_fin")
                        .HasColumnType("interval")
                        .HasColumnName("heure_fin");

                    b.Property<int>("id_cla")
                        .HasColumnType("integer")
                        .HasColumnName("id_cla");

                    b.Property<int>("id_enseignant")
                        .HasColumnType("integer")
                        .HasColumnName("id_enseignant");

                    b.Property<int>("id_matiere")
                        .HasColumnType("integer")
                        .HasColumnName("id_matiere");

                    b.Property<int>("id_salle")
                        .HasColumnType("integer")
                        .HasColumnName("id_salle");

                    b.Property<int>("id_semestre")
                        .HasColumnType("integer")
                        .HasColumnName("id_semestre");

                    b.Property<string>("jour")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jour");

                    b.HasKey("id_seance");

                    b.HasIndex("EmploiDuTempsIdEdt");

                    b.HasIndex("id_cla");

                    b.HasIndex("id_enseignant");

                    b.HasIndex("id_matiere");

                    b.HasIndex("id_salle");

                    b.HasIndex("id_semestre");

                    b.ToTable("seances");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Semestre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_semestre");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_semestre");

                    b.HasKey("Id");

                    b.ToTable("semestres");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_uti");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mdp_uti");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_uti");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom_uti");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_uti");

                    b.HasKey("Id");

                    b.ToTable("utilisateurs");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.EmploiDuTemps", b =>
                {
                    b.HasOne("GestionSallesEtEDT.Api.Models.AnneeUniversitaire", "AnneeUniversitaire")
                        .WithMany()
                        .HasForeignKey("IdAnnee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionSallesEtEDT.Api.Models.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("IdClasse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionSallesEtEDT.Api.Models.Semestre", "Semestre")
                        .WithMany()
                        .HasForeignKey("IdSemestre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnneeUniversitaire");

                    b.Navigation("Classe");

                    b.Navigation("Semestre");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Enseignant", b =>
                {
                    b.HasOne("GestionSallesEtEDT.Api.Models.Utilisateur", "Utilisateur")
                        .WithOne("Enseignant")
                        .HasForeignKey("GestionSallesEtEDT.Api.Models.Enseignant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Etudiant", b =>
                {
                    b.HasOne("GestionSallesEtEDT.Api.Models.Classe", "Classe")
                        .WithMany("Etudiants")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionSallesEtEDT.Api.Models.Utilisateur", "Utilisateur")
                        .WithOne("Etudiant")
                        .HasForeignKey("GestionSallesEtEDT.Api.Models.Etudiant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Seance", b =>
                {
                    b.HasOne("GestionSallesEtEDT.Api.Models.EmploiDuTemps", null)
                        .WithMany("Seances")
                        .HasForeignKey("EmploiDuTempsIdEdt");

                    b.HasOne("GestionSallesEtEDT.Api.Models.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("id_cla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionSallesEtEDT.Api.Models.Enseignant", "Enseignant")
                        .WithMany("Seances")
                        .HasForeignKey("id_enseignant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionSallesEtEDT.Api.Models.Matiere", "Matiere")
                        .WithMany()
                        .HasForeignKey("id_matiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionSallesEtEDT.Api.Models.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("id_salle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionSallesEtEDT.Api.Models.Semestre", "Semestre")
                        .WithMany()
                        .HasForeignKey("id_semestre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Enseignant");

                    b.Navigation("Matiere");

                    b.Navigation("Salle");

                    b.Navigation("Semestre");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Classe", b =>
                {
                    b.Navigation("Etudiants");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.EmploiDuTemps", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Enseignant", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Utilisateur", b =>
                {
                    b.Navigation("Enseignant");

                    b.Navigation("Etudiant");
                });
#pragma warning restore 612, 618
        }
    }
}
