// <auto-generated />
using System;
using GestionSallesEtEDT.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionSallesEtEDT.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260713145534_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Classe", b =>
                {
                    b.Property<int>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClasse"));

                    b.Property<int>("IdParcours")
                        .HasColumnType("integer")
                        .HasColumnName("id_parcours");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("niveau");

                    b.HasKey("IdClasse");

                    b.HasIndex("IdParcours");

                    b.ToTable("classes");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Enseignant", b =>
                {
                    b.Property<int>("IdEnseignant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_enseignant");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEnseignant"));

                    b.Property<string>("Civilite")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("civilite");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.HasKey("IdEnseignant");

                    b.ToTable("enseignants");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Matiere", b =>
                {
                    b.Property<int>("IdMatiere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_matiere");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMatiere"));

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("couleur");

                    b.Property<string>("NomMatiere")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_matiere");

                    b.HasKey("IdMatiere");

                    b.ToTable("matieres");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Mention", b =>
                {
                    b.Property<int>("IdMention")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_mention");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMention"));

                    b.Property<string>("NomMention")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_mention");

                    b.HasKey("IdMention");

                    b.ToTable("mentions");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Parcours", b =>
                {
                    b.Property<int>("IdParcours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_parcours");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdParcours"));

                    b.Property<int>("IdMention")
                        .HasColumnType("integer")
                        .HasColumnName("id_mention");

                    b.Property<string>("NomParcours")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_parcours");

                    b.HasKey("IdParcours");

                    b.HasIndex("IdMention");

                    b.ToTable("parcours");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("ReplacedBy")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Salle", b =>
                {
                    b.Property<int>("IdSalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_salle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSalle"));

                    b.Property<int>("Capacite")
                        .HasColumnType("integer")
                        .HasColumnName("capacite");

                    b.Property<string>("NomSalle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_salle");

                    b.HasKey("IdSalle");

                    b.ToTable("salles");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Seance", b =>
                {
                    b.Property<int>("IdSeance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_seance");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSeance"));

                    b.Property<string>("HeureDebut")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("heure_debut");

                    b.Property<string>("HeureFin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("heure_fin");

                    b.Property<int>("IdClasse")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.Property<int>("IdEnseignant")
                        .HasColumnType("integer")
                        .HasColumnName("id_enseignant");

                    b.Property<int>("IdMatiere")
                        .HasColumnType("integer")
                        .HasColumnName("id_matiere");

                    b.Property<int>("IdSalle")
                        .HasColumnType("integer")
                        .HasColumnName("id_salle");

                    b.Property<string>("Jour")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jour");

                    b.HasKey("IdSeance");

                    b.HasIndex("IdClasse");

                    b.HasIndex("IdEnseignant");

                    b.HasIndex("IdMatiere");

                    b.HasIndex("IdSalle");

                    b.ToTable("seances");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mot_de_passe");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdUtilisateur");

                    b.ToTable("utilisateurs");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Classe", b =>
                {
                    b.HasOne("GestionSallesEtEDT.Api.Models.Parcours", "Parcours")
                        .WithMany()
                        .HasForeignKey("IdParcours")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Parcours", b =>
                {
                    b.HasOne("GestionSallesEtEDT.Api.Models.Mention", "Mention")
                        .WithMany()
                        .HasForeignKey("IdMention")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mention");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("GestionSallesEtEDT.Api.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GestionSallesEtEDT.Api.Models.Seance", b =>
                {
                    b.HasOne("GestionSallesEtEDT.Api.Models.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("IdClasse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionSallesEtEDT.Api.Models.Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("IdEnseignant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionSallesEtEDT.Api.Models.Matiere", "Matiere")
                        .WithMany()
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionSallesEtEDT.Api.Models.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("IdSalle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Enseignant");

                    b.Navigation("Matiere");

                    b.Navigation("Salle");
                });
#pragma warning restore 612, 618
        }
    }
}
